services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env  
    depends_on:
      - db  
    restart: always  
    volumes:
      - ./uploads:/app/uploads  
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2580"
      POSTGRES_DB: ecommerce
    volumes:
      - pg_data:/var/lib/postgresql/data  

volumes:
  pg_data:      